In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.1


## NumPy Functions

In [3]:
a = [1,2,3,4,5]
myArr = np.array(a)
myArr

array([1, 2, 3, 4, 5])

In [4]:
print(type(myArr))

<class 'numpy.ndarray'>


In [5]:
myArr2 = np.array([4,3,2,1])
myArr2

array([4, 3, 2, 1])

In [6]:
print(type(myArr2))

<class 'numpy.ndarray'>


In [7]:
a = [[1,2,3],[4,5,6],[7,8,9]]
myArr3 = np.array(a)
myArr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print("ndim:",myArr3.ndim)
print("shape:",myArr3.shape)

ndim: 2
shape: (3, 3)


## zeros() and ones() (same)

In [9]:
myArr4 = np.zeros(5)
myArr4

array([0., 0., 0., 0., 0.])

In [10]:
myArr5 = np.zeros((3,4))
myArr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
myArr6 = np.eye(5)
myArr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
myArr7 = np.eye(3,4)
myArr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
myArr8 = np.diag([1,2,3,4,5])
myArr8

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [14]:
np.diag(myArr8)

array([1, 2, 3, 4, 5])

In [15]:
myArr9 = np.random.randint(1,50,13)
myArr9

array([46, 39, 21, 32, 27, 19, 13, 46,  8, 21, 45,  5,  5])

In [16]:
myArr10 = np.random.rand(5)
myArr10

array([0.84935059, 0.01374307, 0.02740737, 0.6720044 , 0.15219493])

In [17]:
myArr11 = np.random.rand(6,7)
myArr11

array([[0.90839226, 0.26735924, 0.50269721, 0.78593704, 0.51483978,
        0.24060189, 0.49650985],
       [0.05098397, 0.72635706, 0.64439978, 0.55427184, 0.91469271,
        0.81160005, 0.94932364],
       [0.35691819, 0.19916972, 0.58071587, 0.50732426, 0.90120835,
        0.89612701, 0.52901529],
       [0.39351386, 0.33119792, 0.40360974, 0.37638185, 0.1596475 ,
        0.52671308, 0.70968284],
       [0.55009029, 0.73327584, 0.50501322, 0.99207595, 0.74817676,
        0.12566773, 0.75767022],
       [0.67611786, 0.05673596, 0.28494911, 0.29428802, 0.85571014,
        0.77139193, 0.89687934]])

In [18]:
myArr9[2:5]

array([21, 32, 27])

In [19]:
myArr9[4::2]

array([27, 13,  8, 45,  5])

In [20]:
myArr11[::3][::]

array([[0.90839226, 0.26735924, 0.50269721, 0.78593704, 0.51483978,
        0.24060189, 0.49650985],
       [0.39351386, 0.33119792, 0.40360974, 0.37638185, 0.1596475 ,
        0.52671308, 0.70968284]])

In [21]:
myArr11[::,::2]

array([[0.90839226, 0.50269721, 0.51483978, 0.49650985],
       [0.05098397, 0.64439978, 0.91469271, 0.94932364],
       [0.35691819, 0.58071587, 0.90120835, 0.52901529],
       [0.39351386, 0.40360974, 0.1596475 , 0.70968284],
       [0.55009029, 0.50501322, 0.74817676, 0.75767022],
       [0.67611786, 0.28494911, 0.85571014, 0.89687934]])

In [22]:
myArr12 = np.random.randint(1,50,12)
myArr12

array([ 7,  3, 29, 48, 18, 11, 34, 24, 26, 32, 10, 26])

In [23]:
myArr13 = myArr12.reshape(6,2)
myArr13

array([[ 7,  3],
       [29, 48],
       [18, 11],
       [34, 24],
       [26, 32],
       [10, 26]])

In [24]:
myArr14 = myArr12.reshape(2,2,3)
myArr14

array([[[ 7,  3, 29],
        [48, 18, 11]],

       [[34, 24, 26],
        [32, 10, 26]]])

In [25]:
myArr15 = myArr12.reshape(6,-1)
myArr15

array([[ 7,  3],
       [29, 48],
       [18, 11],
       [34, 24],
       [26, 32],
       [10, 26]])

In [26]:
myArr16 = myArr12.reshape(-1,3)
myArr16

array([[ 7,  3, 29],
       [48, 18, 11],
       [34, 24, 26],
       [32, 10, 26]])

In [27]:
np.random.seed(12)
myArr17 = np.random.randint(1,100,10)
myArr17

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [28]:
np.random.seed(111)
myArr18 = np.random.randint(1, 500, 30).reshape(5,6)
myArr18

array([[341, 365, 469, 213,  87, 276],
       [170, 323, 119, 467, 297, 456],
       [442,   8, 269, 267, 450, 369],
       [217, 285, 271, 419,  22,  55],
       [201,  38, 461, 231, 187, 269]])

In [30]:
myArr18[1:4, 1:5]

array([[323, 119, 467, 297],
       [  8, 269, 267, 450],
       [285, 271, 419,  22]])

In [31]:
myArr18[::2, 1::2]

array([[365, 213, 276],
       [  8, 267, 369],
       [ 38, 231, 269]])

In [33]:
np.diag(myArr18)

array([341, 323, 269, 419, 187])

In [35]:
myArr19 = np.array([1,2,3,4,5,6,7,8,9,10])
myArr19view = myArr19[3:8]
print(myArr19)
print(myArr19view)
myArr19view[:] = 0
print(myArr19)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8]
[ 1  2  3  0  0  0  0  0  9 10]


In [36]:
myArr19 = np.array([1,2,3,4,5,6,7,8,9,10])
myArr19view = myArr19[3:8].copy()
print(myArr19)
print(myArr19view)
myArr19view[:] = 0
print(myArr19)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]


In [37]:
myArr20 = np.arange(1,16)
myArr20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
myArr20 > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [41]:
myArr20 % 2 == 1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [43]:
myArr21[myArr20 % 3 == 0]
myArr21

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True])

In [50]:
myArr21[myArr20 > 7]

array([False,  True, False, False,  True, False, False,  True])

In [51]:
myArr21 = myArr20[myArr20 < 7]
myArr21

array([1, 2, 3, 4, 5, 6])

In [57]:
myArr20[myArr20 % 2 == 0] = 100
myArr20

array([  1, 100,   3, 100,   5, 100,   7, 100,   9, 100,  11, 100,  13,
       100,  15])

In [61]:
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
print(a)
print(b)
print(a*b)
print(a.dot(b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [62]:
a = np.array([3,23,42,5,2,21])
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))

2
42
4
2
[1.73205081 4.79583152 6.4807407  2.23606798 1.41421356 4.58257569]
[ 0.14112001 -0.8462204  -0.91652155 -0.95892427  0.90929743  0.83665564]
[-0.9899925  -0.53283302 -0.39998531  0.28366219 -0.41614684 -0.54772926]


In [63]:
a = np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [64]:
a = np.linspace(2,10,5)
a

array([ 2.,  4.,  6.,  8., 10.])

In [70]:
a = np.array([1,2,3,4,5,6,5,6,7,8,9,10]).reshape(4,3)
print(a)
print(np.max(a, axis = 1))
print(np.max(a, axis = 0))
print(np.sum(a, axis = 1))
print(np.cumsum(a))

[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]
[ 3  6  7 10]
[ 8  9 10]
[ 6 15 18 27]
[ 1  3  6 10 15 21 26 32 39 47 56 66]


In [78]:
np.random.seed(122)
a = np.random.randint(1,50,20)
a

array([48, 27, 11, 13, 17, 45, 16, 35, 16, 43, 22, 32, 42,  7, 15, 36, 37,
       32, 20, 14])

In [79]:
np.random.shuffle(a)
a

array([17, 43, 20, 13, 37, 11, 27, 15, 42, 35, 16, 45, 14, 32, 22, 16, 32,
       36,  7, 48])

In [80]:
np.unique(a)

array([ 7, 11, 13, 14, 15, 16, 17, 20, 22, 27, 32, 35, 36, 37, 42, 43, 45,
       48])

In [81]:
np.unique(a).size

18

In [83]:
a = np.array([1,2,1,4,2,4,3,6,3])
np.unique(a, return_index = True, return_counts = True)

(array([1, 2, 3, 4, 6]), array([0, 1, 6, 3, 7]), array([2, 2, 2, 2, 1]))

In [86]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [89]:
a = np.arange(1,16)
b = np.where(a > 5)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)


In [90]:
b = np.where(a % 5 == 0)
b

(array([ 4,  9, 14]),)

In [92]:
b = np.where(a % 2 == 0)
b

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [93]:
c = np.searchsorted(a,12)
c

11